name: Build Executables

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install tkinter
        run: sudo apt-get update && sudo apt-get install -y python3-tk

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build executable
        run: pyinstaller --onefile --windowed -n dna_seq_analyser --icon=assets/icon.png apps_gui.py

      - name: Bundle output
        run: |
          mkdir release-bundle
          cp dist/dna_seq_analyser release-bundle/
          cp -r assets release-bundle/
          cp -r test_data release-bundle/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DNASeq-Analyser-linux
          path: release-bundle/

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build executable
        run: pyinstaller --onefile --windowed -n dna_seq_analyser --icon=assets/icon.ico apps_gui.py

      - name: Bundle output
        run: |
          mkdir release-bundle
          copy dist\dna_seq_analyser.exe release-bundle\
          xcopy /E /I test_data release-bundle\test_data

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DNASeq-Analyser-windows
          path: release-bundle/

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build executable
        run: pyinstaller --onefile --windowed -n dna_seq_analyser --icon=assets/icon.icns apps_gui.py

      - name: Bundle output
        run: |
          mkdir release-bundle
          cp dist/dna_seq_analyser release-bundle/
          cp -r test_data release-bundle/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: DNASeq-Analyser-macos
          path: release-bundle/
